services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      # Identifiants Root (Admin)
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      # Variables transmises au script init-db.js
      DATABASE_NAME: ${DATABASE_NAME}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: migration-app
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      # Permet au script Python d'accéder au fichier CSV sur ton Mac
      - ./healthcare_dataset.csv:/app/healthcare_dataset.csv
    environment:
      # Variables utilisées par le script Python pour la connexion
      DATABASE_NAME: ${DATABASE_NAME}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGODB_URI: mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@mongodb:27017/${DATABASE_NAME}

volumes:
  mongodb_data: