services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      DATABASE_NAME:        ${DATABASE_NAME}
      MONGO_APP_USER:       ${MONGO_APP_USER}
      MONGO_APP_PASSWORD:   ${MONGO_APP_PASSWORD}
      MONGO_AUDIT_USER:     ${MONGO_AUDIT_USER}
      MONGO_AUDIT_PASSWORD: ${MONGO_AUDIT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  app:
    build: .
    container_name: migration-app
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./healthcare_dataset.csv:/app/healthcare_dataset.csv
    environment:
      DATABASE_NAME:        ${DATABASE_NAME}
      MONGO_ROOT_USER:      ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD:  ${MONGO_ROOT_PASSWORD}
      MONGO_APP_USER:       ${MONGO_APP_USER}
      MONGO_APP_PASSWORD:   ${MONGO_APP_PASSWORD}
      MONGO_AUDIT_USER:     ${MONGO_AUDIT_USER}
      MONGO_AUDIT_PASSWORD: ${MONGO_AUDIT_PASSWORD}
      MONGODB_URI: mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@mongodb:27017/${DATABASE_NAME}
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge